model_name: v5.1
description: 增加rssi
model_save_dir: /server19/lmj/github/wifi_localization/run
seed: 2023

epoch: 5
lr_f: 0.0003
lr_min: 0.0002
multiplier: 1
warmup_epoch: 1
grad_clip: 5

window_size: 128
stride: 2