model_name: office1
description: the best
model_save_dir: run/
seed: 2023

epoch: 10
lr_f: 0.0003
lr_min: 0.0002
multiplier: 1
warmup_epoch: 1
grad_clip: 5

window_size: 128
sampling_f: 48
stride: 2
subcarrier: [24,32]

amp: True
phase_diff: True
in_channels: 16

inference:
  TASK: task1
  Threshold: 0.8
  Room: 4
  M: 8
  duration: 300
  is_pre_num: True
  result_path: results/1_officeA.txt