model_name: office2
description: the best
model_save_dir: run/
seed: 2023

epoch: 10
lr_f: 0.0003
lr_min: 0.0002
multiplier: 1
warmup_epoch: 1
grad_clip: 5

window_size: 128
sampling_f: 96
stride: 2
subcarrier: [24,32]

amp: False
phase_diff: True
in_channels: 8

inference:
  TASK: task2
  Threshold: 0.8
  Room: 3
  M: 6
  duration: 300
  is_pre_num: False
  result_path: results/2_officeB.txt